#schedules:
#- cron: "0 0 * * *"
#  displayName: Daily
#  branches:
#    include:
#    - main
#  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_type: ubuntu2204
    image_name: az-ubuntu2204-latest
    image_readme_name: Ubuntu2204-Readme.md
    image_template_name: ubuntu-22.04.pkr.hcl
    agent_pool: 'Azure Pipelines'
    variable_group_name: 'Azullian-AgentImages-Ubuntu2204'
    create_release: false
    repository_ref: 'self'